In [9]:
import numpy as np 
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray[0])):
        for k in range(len(a_ndarray)):
            result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [10]:
import numpy as np 
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
result = np.dot(a_ndarray,b_ndarray)
ret = a_ndarray@b_ndarray
print(result)
print(ret)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [12]:
import numpy as np 
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ret = 0
for i in range(len(a_ndarray)):
    ret += a_ndarray[0][i] * b_ndarray[i][0]
print(ret)

6


In [20]:
import numpy as np 
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
def matrix_mult(a_ndarray= [],b_ndarray= []):
    result = np.array([[0,0,0],[0,0,0],[0,0,0]])
    for i in range(len(a_ndarray)):
        for j in range(len(b_ndarray[0])):
            for k in range(len(a_ndarray)):
                result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
    print(result)
matrix_mult(a_ndarray,b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [22]:
import numpy as np 
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
b_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
def matrix_mult(a_ndarray= [],b_ndarray= []):
    result = np.array([[0,0,0],[0,0,0],[0,0,0]])
    for i in range(len(a_ndarray)):
        for j in range(len(b_ndarray[0])):
            for k in range(len(a_ndarray)):
                result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
    print(result)
matrix_mult(a_ndarray,b_ndarray)

[[ 21 -18   1]
 [-66  57   8]
 [  0   0   0]]


In [27]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
def matrix_product(a_ndarray = []):
    one_way = np.transpose(a_ndarray)
    return np.dot(a_ndarray,one_way),np.dot(one_way,a_ndarray)
print(matrix_product(a_ndarray))

[[14  4]
 [ 4 77]]
